@PORT=3001
POST http://localhost:{{PORT}}/api/users/
Content-Type: application/json

{
  	"fullname": "Pekka Pouta",
  	"password": "salasana",
        "email": "pekkas@mtv3.fi",
        "nickname": "pilvi"
}