@PORT=3001
POST http://localhost:{{PORT}}/api/users/
Content-Type: application/json

{
  	"fullname": "Pekka Puupää",
  	"password": "salasana",
        "email": "pekkasession@session.fi",
        "nickname": "Pirkka"
}